# This is workflow name
name: CICD workflow

# Manual click deliver workflow when user needs
on:
  workflow_dispatch:
    
  # push:
  #   branches: [main]

jobs:
  #every job needs a separate runner this is known as parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone from Github"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
     - name: build the docker image
       run: echo "Docker run to build image"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: run tests for image build
        run: echo "Testing the container"
  deploy:
     needs: [build,test]
     runs-on: ubuntu-latest
     steps:
       - name: Deploying the app
         run: echo "Docker compose deployed the app"
       
